//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.FrameWork
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.About_Us = new HashSet<About_Us>();
            this.PROPERTies = new HashSet<PROPERTy>();
            this.PROPERTies1 = new HashSet<PROPERTy>();
        }
    
        public int ID { get; set; }

        [Required(ErrorMessage = "Email can't be empty")]
        [StringLength(50)]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Password can't be empty")]
        [StringLength(50)]
        public string Password { get; set; }

        [Required(ErrorMessage = "FullName can't be empty")]
        [StringLength(50)]
        public string FullName { get; set; }

        [Required(ErrorMessage = "Phone can't be empty")]
        [StringLength(15)]
        public string Phone { get; set; }
        [Required(ErrorMessage = "Address can't be empty")]

        [StringLength(100)]
        public string Address { get; set; }
        public string Role { get; set; }
        public Nullable<bool> Status { get; set; }
        public string GroupID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<About_Us> About_Us { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROPERTy> PROPERTies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROPERTy> PROPERTies1 { get; set; }
    }
}
