// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TEDU_MVC.AcceptanceTests.Feature
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class ViewDetailProjectFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ViewDetailProject.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "View Detail Project", "As a potential customer\r\nI want to see the details of a properties\r\nSo that T can" +
                    " better decide to buy it.", ProgrammingLanguage.CSharp, new string[] {
                        "web"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "View Detail Project")))
            {
                TEDU_MVC.AcceptanceTests.Feature.ViewDetailProjectFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 8
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Password",
                        "FullName",
                        "Phone",
                        "Address",
                        "Role",
                        "Status",
                        "GroupID"});
            table1.AddRow(new string[] {
                        "lythihuyenchau@gmail.com",
                        "123456",
                        "LyChau",
                        "0123456789",
                        "Quan 1",
                        "1",
                        "True",
                        "SALE"});
            table1.AddRow(new string[] {
                        "buibao1997@gmail.com",
                        "123456",
                        "ShayneBui",
                        "0123456789",
                        "Quan 1",
                        "2",
                        "False",
                        "AGENCY"});
#line 9
testRunner.Given("the following property Agency", ((string)(null)), table1, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "PropertyName",
                        "Content",
                        "Price",
                        "PropertyType",
                        "District",
                        "Ward_ID",
                        "Street_ID",
                        "UserID",
                        "StatusID",
                        "Feature"});
            table2.AddRow(new string[] {
                        "Gojko Adzic",
                        "Specification By Example",
                        "1200",
                        "Apartment",
                        "Ba Vì",
                        "Chu Minh",
                        "Đảo Ngắn",
                        "lythihuyenchau@gmail.com",
                        "Đã duyệt",
                        "Ban công"});
            table2.AddRow(new string[] {
                        "Eckhart Tolle",
                        "The Power of Now",
                        "1200",
                        "Villa",
                        "Chương Mỹ",
                        "Đại Yên",
                        "Tân Bình",
                        "buibao1997@gmail.com",
                        "Đã duyệt",
                        "Chỗ đậu xe"});
            table2.AddRow(new string[] {
                        "Jeff Sutherland",
                        "Scrum: The Art of Doing Twice the Work in Half the Time",
                        "1600",
                        "Office",
                        "Ba Vì",
                        "Chu Minh",
                        "Đảo Ngắn",
                        "lythihuyenchau@gmail.com",
                        "Đã duyệt",
                        "Thang máy"});
            table2.AddRow(new string[] {
                        "Mitch Lacey",
                        "The Scrum Field Guide",
                        "1500",
                        "House",
                        "Chương Mỹ",
                        "Đại Yên",
                        "Tân Bình",
                        "buibao1997@gmail.com",
                        "Đã duyệt",
                        "Vườn"});
            table2.AddRow(new string[] {
                        "Martin Fowler",
                        "Analysis Patterns",
                        "5000",
                        "Apartment",
                        "Ba Vì",
                        "Chu Minh",
                        "Đảo Ngắn",
                        "lythihuyenchau@gmail.com",
                        "Đã duyệt",
                        "Phòng tập Gym"});
            table2.AddRow(new string[] {
                        "Eric Evans",
                        "Domain Driven Design",
                        "4600",
                        "Villa",
                        "Chương Mỹ",
                        "Đại Yên",
                        "Tân Bình",
                        "buibao1997@gmail.com",
                        "Đã duyệt",
                        "Nhà bếp"});
            table2.AddRow(new string[] {
                        "Ted Pattison",
                        "Inside Windows SharePoint Services",
                        "1300",
                        "Office",
                        "Ba Vì",
                        "Chu Minh",
                        "Đảo Ngắn",
                        "lythihuyenchau@gmail.com",
                        "Đã duyệt",
                        "Phòng giặc ủi"});
            table2.AddRow(new string[] {
                        "Lisa Crispin and Janet Gregory",
                        "Agile Testing",
                        "2000",
                        "House",
                        "Chương Mỹ",
                        "Đại Yên",
                        "Tân Bình",
                        "buibao1997@gmail.com",
                        "Đã duyệt",
                        "Cho nuôi thú cưng"});
            table2.AddRow(new string[] {
                        "Esther Derby and Diana Larsen",
                        "Agile Retrospectives",
                        "1600",
                        "Apartment",
                        "Ba Vì",
                        "Chu Minh",
                        "Đảo Ngắn",
                        "lythihuyenchau@gmail.com",
                        "Đã duyệt",
                        "Hồ bơi"});
#line 13
testRunner.And("the following property and list feature \'Ban công\'", ((string)(null)), table2, "And ");
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("The PropertyName, the content of it can show")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "View Detail Project")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("web")]
        public virtual void ThePropertyNameTheContentOfItCanShow()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The PropertyName, the content of it can show", ((string[])(null)));
#line 25
this.ScenarioSetup(scenarioInfo);
#line 8
this.FeatureBackground();
#line 26
testRunner.Given("I am Home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 27
testRunner.When("I open the details of \'Eckhart Tolle\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "PropertyName",
                        "Content",
                        "Price",
                        "PropertyType",
                        "District",
                        "Ward_ID",
                        "Street_ID",
                        "UserID",
                        "StatusID",
                        "Feature"});
            table3.AddRow(new string[] {
                        "Eckhart Tolle",
                        "The Power of Now",
                        "1200",
                        "Villa",
                        "Chương Mỹ",
                        "Đại Yên",
                        "Tân Bình",
                        "buibao1997@gmail.com",
                        "Đã duyệt",
                        "Chỗ đậu xe"});
#line 28
testRunner.Then("The details PropertyName should show", ((string)(null)), table3, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
