// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TEDU_MVC.AcceptanceTests.Feature
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class PostPropertyBackgroundFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "PostPropertyBackground.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "PostPropertyBackground", "In order to avoid silly mistakes\r\nAs a math idiot\r\nI want to be told the sum of t" +
                    "wo numbers", ProgrammingLanguage.CSharp, new string[] {
                        "automated",
                        "*update"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "PostPropertyBackground")))
            {
                TEDU_MVC.AcceptanceTests.Feature.PostPropertyBackgroundFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 8
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "PropertyName",
                        "Content",
                        "Price",
                        "PropertyType",
                        "District",
                        "UserID",
                        "StatusID"});
            table1.AddRow(new string[] {
                        "Gojko Adzic",
                        "Specification By Example",
                        "1200",
                        "1",
                        "2",
                        "1",
                        "3"});
            table1.AddRow(new string[] {
                        "Eckhart Tolle",
                        "The Power of Now",
                        "1200",
                        "2",
                        "3",
                        "12",
                        "3"});
            table1.AddRow(new string[] {
                        "Jeff Sutherland",
                        "Scrum: The Art of Doing Twice the Work in Half the Time",
                        "1600",
                        "3",
                        "4",
                        "1",
                        "3"});
            table1.AddRow(new string[] {
                        "Mitch Lacey",
                        "The Scrum Field Guide",
                        "1500",
                        "4",
                        "3",
                        "12",
                        "3"});
            table1.AddRow(new string[] {
                        "Martin Fowler",
                        "Analysis Patterns",
                        "5000",
                        "1",
                        "2",
                        "1",
                        "3"});
            table1.AddRow(new string[] {
                        "Eric Evans",
                        "Domain Driven Design",
                        "4600",
                        "2",
                        "4",
                        "12",
                        "3"});
            table1.AddRow(new string[] {
                        "Ted Pattison",
                        "Inside Windows SharePoint Services",
                        "3100",
                        "3",
                        "3",
                        "1",
                        "3"});
            table1.AddRow(new string[] {
                        "Lisa Crispin and Janet Gregory",
                        "Agile Testing",
                        "2000",
                        "4",
                        "2",
                        "12",
                        "3"});
            table1.AddRow(new string[] {
                        "Esther Derby and Diana Larsen",
                        "Agile Retrospectives",
                        "1600",
                        "1",
                        "4",
                        "1",
                        "3"});
#line 9
 testRunner.Given("the following property", ((string)(null)), table1, "Given ");
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Successfull Creating New Property")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "PostPropertyBackground")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("automated")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("*update")]
        public virtual void SuccessfullCreatingNewProperty()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Successfull Creating New Property", ((string[])(null)));
#line 22
this.ScenarioSetup(scenarioInfo);
#line 8
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "PropertyName",
                        "Content",
                        "Price",
                        "PropertyType",
                        "District",
                        "UserID",
                        "StatusID"});
            table2.AddRow(new string[] {
                        "New Create Property",
                        "Example",
                        "1200",
                        "1",
                        "2",
                        "1",
                        "3"});
#line 23
 testRunner.When("I input the following information", ((string)(null)), table2, "When ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "PropertyName",
                        "Content",
                        "Price",
                        "PropertyType",
                        "District",
                        "UserID",
                        "StatusID"});
            table3.AddRow(new string[] {
                        "Gojko Adzic",
                        "Specification By Example",
                        "1200",
                        "1",
                        "2",
                        "1",
                        "3"});
            table3.AddRow(new string[] {
                        "Eckhart Tolle",
                        "The Power of Now",
                        "1200",
                        "2",
                        "3",
                        "12",
                        "3"});
            table3.AddRow(new string[] {
                        "Jeff Sutherland",
                        "Scrum: The Art of Doing Twice the Work in Half the Time",
                        "1600",
                        "3",
                        "4",
                        "1",
                        "3"});
            table3.AddRow(new string[] {
                        "Mitch Lacey",
                        "The Scrum Field Guide",
                        "1500",
                        "4",
                        "3",
                        "12",
                        "3"});
            table3.AddRow(new string[] {
                        "Martin Fowler",
                        "Analysis Patterns",
                        "5000",
                        "1",
                        "2",
                        "1",
                        "3"});
            table3.AddRow(new string[] {
                        "Eric Evans",
                        "Domain Driven Design",
                        "4600",
                        "2",
                        "4",
                        "12",
                        "3"});
            table3.AddRow(new string[] {
                        "Ted Pattison",
                        "Inside Windows SharePoint Services",
                        "3100",
                        "3",
                        "3",
                        "1",
                        "3"});
            table3.AddRow(new string[] {
                        "Lisa Crispin and Janet Gregory",
                        "Agile Testing",
                        "2000",
                        "4",
                        "2",
                        "12",
                        "3"});
            table3.AddRow(new string[] {
                        "Esther Derby and Diana Larsen",
                        "Agile Retrospectives",
                        "1600",
                        "1",
                        "4",
                        "1",
                        "3"});
            table3.AddRow(new string[] {
                        "New Create Property",
                        "Example",
                        "1200",
                        "1",
                        "2",
                        "1",
                        "3"});
#line 26
 testRunner.Then("the list of books should update", ((string)(null)), table3, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
