// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TEDU_MVC.AcceptanceTests.Feature
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class EditTest2Feature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
#line 1 "UC.06.EditProjectAgency.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "EditTest2", "\tIn order to avoid silly mistakes\r\n\tAs a math idiot\r\n\tI want edit a project", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "EditTest2")))
            {
                global::TEDU_MVC.AcceptanceTests.Feature.EditTest2Feature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(TestContext);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "PropertyName",
                        "PropertyType",
                        "Content",
                        "Street",
                        "Ward",
                        "District",
                        "Price",
                        "Area",
                        "BedRoom",
                        "BathRoom",
                        "PackingPlace"});
            table1.AddRow(new string[] {
                        "PIS Top Apartment",
                        "1",
                        "The surrounding neighborhood is very much localized with a great number of local " +
                            "shops.",
                        "748",
                        "2",
                        "2",
                        "10000",
                        "120m2",
                        "3",
                        "2",
                        "1"});
            table1.AddRow(new string[] {
                        "ViLa Q7",
                        "2",
                        "Brand new apartments with unbelievable river and city view, completely renovated " +
                            "and tastefully furnished.",
                        "750",
                        "3",
                        "2",
                        "70000",
                        "120m2",
                        "3",
                        "4",
                        "1"});
            table1.AddRow(new string[] {
                        "PIS Serviced Apartment – Style",
                        "3",
                        "The well equipped kitchen is opened on a cozy living room and a dining area with " +
                            "table and chairs..",
                        "749",
                        "4",
                        "2",
                        "30000",
                        "130m2",
                        "2",
                        "3",
                        "1"});
            table1.AddRow(new string[] {
                        "Vinhomes Central Park L2 – Duong’s Apartment",
                        "2",
                        "Vinhomes Central Park is a new development that is in the heart of everything tha" +
                            "t Ho Chi Minh has to offer.",
                        "755",
                        "33",
                        "3",
                        "110000",
                        "150m2",
                        "4",
                        "2",
                        "1"});
            table1.AddRow(new string[] {
                        "Saigon Pearl Ruby Block",
                        "1",
                        "Studio apartment at central of CBD, nearby Ben Thanh market, Bui Vien Backpacker " +
                            "Area, 23/9 park…",
                        "758",
                        "35",
                        "3",
                        "30000",
                        "130m2",
                        "3",
                        "5",
                        "1"});
#line 7
 testRunner.Given("I want Edit follow this Catalog", ((string)(null)), table1, "Given ");
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("success edit project")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "EditTest2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        public virtual void SuccessEditProject()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("success edit project", new string[] {
                        "mytag"});
#line 16
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "PropertyName",
                        "PropertyType",
                        "Content",
                        "Street",
                        "Ward",
                        "District",
                        "Price",
                        "Area",
                        "BedRoom",
                        "BathRoom",
                        "PackingPlace"});
            table2.AddRow(new string[] {
                        "Căn hộ Saigon Pearl",
                        "2",
                        "View Đẹp và sang trọng",
                        "750",
                        "3",
                        "3",
                        "50000",
                        "200m2",
                        "4",
                        "3",
                        "4"});
#line 17
 testRunner.When("I editting  follow this data", ((string)(null)), table2, "When ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "PropertyName",
                        "PropertyType",
                        "Content",
                        "Street",
                        "Ward",
                        "District",
                        "Price",
                        "Area",
                        "BedRoom",
                        "BathRoom",
                        "PackingPlace"});
            table3.AddRow(new string[] {
                        "Căn hộ Saigon Pearl",
                        "2",
                        "View Đẹp và sang trọng",
                        "750",
                        "3",
                        "3",
                        "50000",
                        "200m2",
                        "4",
                        "3",
                        "4"});
            table3.AddRow(new string[] {
                        "ViLa Q7",
                        "2",
                        "Brand new apartments with unbelievable river and city view, completely renovated " +
                            "and tastefully furnished.",
                        "750",
                        "3",
                        "2",
                        "70000",
                        "120m2",
                        "3",
                        "4",
                        "1"});
            table3.AddRow(new string[] {
                        "PIS Serviced Apartment – Style",
                        "3",
                        "The well equipped kitchen is opened on a cozy living room and a dining area with " +
                            "table and chairs..",
                        "749",
                        "4",
                        "2",
                        "30000",
                        "130m2",
                        "2",
                        "3",
                        "1"});
            table3.AddRow(new string[] {
                        "Vinhomes Central Park L2 – Duong’s Apartment",
                        "2",
                        "Vinhomes Central Park is a new development that is in the heart of everything tha" +
                            "t Ho Chi Minh has to offer.",
                        "755",
                        "33",
                        "3",
                        "110000",
                        "150m2",
                        "4",
                        "2",
                        "1"});
            table3.AddRow(new string[] {
                        "Saigon Pearl Ruby Block",
                        "1",
                        "Studio apartment at central of CBD, nearby Ben Thanh market, Bui Vien Backpacker " +
                            "Area, 23/9 park…",
                        "758",
                        "35",
                        "3",
                        "30000",
                        "130m2",
                        "3",
                        "5",
                        "1"});
#line 20
 testRunner.Then("After Edit I want see the data same this follow", ((string)(null)), table3, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
